fun main() {
    var fruit: Array<String> = arrayOf("mango", "banana", "papaya", "litchi", "apple")
    println("process 1")
    for (i in 0..fruit.size - 1)
        println("${(i)} -> ${fruit[i]}")
    println("process 2")
    for (i: Int in 0 until fruit.size)
        println("${(i)} -> ${fruit[i]}")
    println("process 3")
    for (i: Int in fruit.size - 1 downTo 0)
        println("$i -> ${fruit[i]}")
    println("process 4")
    for (i: Int in fruit.indices)
        println("$i - > ${fruit[i]}")
    println("process 5")
    for ((i: Int, e: String) in fruit.withIndex())
        println("$i - $e")
    println("process 6")
    for (i:Int in fruit.indices)
        println("${fruit.get(i)} -> $i")
}